export const ROOM_CREATE_REQUEST = 'ROOM_CREATE_REQUEST'
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS'
export const ROOM_CREATE_FAIL = 'ROOM_CREATE_FAIL'

export const ROOM_UPDATE_REQUEST = 'ROOM_UPDATE_REQUEST'
export const ROOM_UPDATE_SUCCESS = 'ROOM_UPDATE_SUCCESS'
export const ROOM_UPDATE_FAIL = 'ROOM_UPDATE_FAIL'

export const ROOM_DELETE_REQUEST = 'ROOM_DELETE_REQUEST'
export const ROOM_DELETE_SUCCESS = 'ROOM_DELETE_SUCCESS'
export const ROOM_DELETE_FAIL = 'ROOM_DELETE_FAIL'